
const CHANNEL_INIT = 1;
const CHANNEL_OPENED = 2;
const CHANNEL_CLOSED = 3;
const CHANNEL_UPDATEBALANCEPROOF = 4;
const CHANNEL_SETTLED = 5;
const CHANNEL_UNLOCKFINISHED = 6;


const BET_INIT = 1;
const BET_LOCK_ONE = 2;
const BET_LOCK_TWO = 3;
const BET_START = 4;
const BET_PREIMAGE = 5;
const BET_FINISH = 6;



module.exports = {
    CHANNEL_INIT,
    CHANNEL_OPENED,
    CHANNEL_CLOSED,
    CHANNEL_UPDATEBALANCEPROOF,
    CHANNEL_SETTLED,
    CHANNEL_UNLOCKFINISHED,

    BET_INIT,
    BET_LOCK_ONE,
    BET_LOCK_TWO,
    BET_START,
    BET_PREIMAGE,
    BET_FINISH,
}